#Requires -Version 5.1
<#
.SYNOPSIS
    Create DIP files for JVA attachments from downloaded files
    
.DESCRIPTION
    Reads the attachment index file created by Download_JVA_Attachments.ps1
    and generates DIP files for OnBase import
    
.EXAMPLE
    .\Create_JVA_DIP_Files.ps1
#>

Import-Module "\\erp311script\Library\PSM1\ERP_mod_logging.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_wmi.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_database.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_file.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_notify.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_datetime.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_util.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_string.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_print.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_hrm.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_fin.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_env.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_exec.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_interface.psm1"
Import-Module "\\erp311script\Library\PSM1\ERP_mod_reporting.psm1"


$env:ENVIRONMENT = "PROD"

if ($env:ENVIRONMENT -eq "PROD") {
    # Production logging handled by module
} else {
    function WriteLog {
        param ([String]$message)
        Write-Host "Log: $message"
    }
}

# Global variables
$script:ProcessDate = (Get-Date -Format "MM/dd/yyyy HH:mm:ss") + " ET"
$script:DocDate = Get-Date -Format "MM/dd/yyyy"

#region Helper Functions

function Get-FileTypeNum {
    param([string]$FileName)
    $extension = [System.IO.Path]::GetExtension($FileName).ToLower()
    switch ($extension) {
        ".pdf"  { return 16 }
        ".doc"  { return 17 }
        ".docx" { return 17 }
        ".xls"  { return 18 }
        ".xlsx" { return 18 }
        default { return 16 }
    }
}

function Get-SHA256Hash {
    param([string]$FilePath)
    if (-not (Test-Path $FilePath)) { return "" }
    try {
        $hash = Get-FileHash -Path $FilePath -Algorithm SHA256
        return $hash.Hash
    } catch {
        WriteLog "Error calculating SHA256 hash: $_"
        return ""
    }
}

function GetUsername {
    # Returns the current Windows username
    return $env:USERNAME
}

#endregion

#region Main Processing

try {
    CreateGlobalVariables $PSCommandPath $PSScriptRoot

    $AttachmentsPath = "\\dlerp311birt\ProcessingCenter\Main\output\JETPDF\JVA\attachments"
    $IndexFilePath = Join-Path $AttachmentsPath "!JVA_attachment_index.txt"
    $DIPFilePath = Join-Path $AttachmentsPath "!JVA_attachment_indexes_DIP.txt"

    $DIP_ProcessingPath = "\\dlerp311birt\onbase\ACC_JournalVouchers\"

    WriteLog "Starting DIP File Creation"
    WriteLog "Attachments Path: $AttachmentsPath"
    WriteLog "Index File: $IndexFilePath"
    WriteLog "DIP File: $DIPFilePath"

    # Check if index file exists
    if (-not (Test-Path $IndexFilePath)) {
        WriteLog "ERROR: Index file not found. Please run Download_JVA_Attachments.ps1 first."
        exit 1
    }

    # Open DIP file for writing
    $dipFileStream = New-Object System.IO.StreamWriter($DIPFilePath, $false, [System.Text.Encoding]::UTF8)

    # Write DIP file header
    $dipHeader = @"
>>>>Self Configuring Tagged DIP<<
>>Dummy Key: Generated by: Task Scheduler - ERP_JVA_Attachments_DIP.ps1
>>Dummy Key: Version: 1.00
>>Dummy Key: Generated on: $script:ProcessDate
>>Dummy Key: Executed by: $(GetUsername)
>>Dummy Key: Log: $global:logname
>>Dummy Key: See the bottom of this file for the total number of attachments.

"@
    $dipFileStream.Write($dipHeader)

    # Read index file
    $indexLines = Get-Content $IndexFilePath
    $headerLine = $indexLines[0]
    $dataLines = $indexLines[1..($indexLines.Length - 1)]

    if ($indexLines.Count -le 1) {
        WriteLog "No data lines found in index file (only headers present)"
        $dataLines = @()
    }

    WriteLog "Found $($dataLines.Length) attachments in index file"

    $dipCount = 0

    foreach ($line in $dataLines) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }

        $dipCount++
        
        # Parse the index line
        $fields = $line -split '\|'
        
        $OBJ_ATT_UNID = $fields[0]
        $ATT_DATE = $fields[1]
        $GUID_FILENAME = $fields[2]
        $FULL_PATH = $fields[3]
        $USER_ID = $fields[4]
        $DESCRIPTION = $fields[5]
        $DOC_ID = $fields[6]
        $DEPT_CD = $fields[7]
        $DOC_ID_OUT = $fields[8]
        $DOC_TYP = $fields[9]
        $DOC_CD = $fields[10]
        $VERS_NO = $fields[11]
        $SG_UNID = $fields[12]
        $SEQ_NO = $fields[13]
        $STATUS = $fields[14]
        $TYPE = $fields[15]
        $COMP_NM = $fields[16]
        $COMP_DESC = $fields[17]
        $ORIGINAL_FILENAME = $fields[18]
        $CURR_FY = $fields[19]
        $CURR_PER = $fields[20]

        # Determine DocTypeName based on DOC_ID prefix
        $docTypeName = ">>DocTypeName: ACC - Journal Voucher"
        if ($DOC_ID -match "^CV") {
            $docTypeName = ">>DocTypeName: ACC - Journal Voucher"
        } elseif ($DOC_ID -match "^EL") {
            $docTypeName = ">>DocTypeName: ACC - Journal Voucher - EL"
        } elseif ($DOC_ID -match "^PA") {
            $docTypeName = ">>DocTypeName: ACC - Journal Voucher - PA"
        } elseif ($DOC_ID -match "^TC") {
            $docTypeName = ">>DocTypeName: ACC - Journal Voucher - TC"
        }

        # Build DIP entry
        $dipEntry = @"
BEGIN:
>>Dummy Key: Original Source: Advantage Attachment $DOC_ID Attachment Number $SEQ_NO
$docTypeName
>>DocDate: $script:DocDate
Date: $ATT_DATE
Vendor-Customer #:
Vendor Name:
Advantage Attachment ID: $OBJ_ATT_UNID
JV #: JVA$DOC_ID
Accounting Period: $CURR_PER/$CURR_FY
Filename: $ORIGINAL_FILENAME
>>Dummy Key: hidden keywords begin here
>>FileTypeNum: $(Get-FileTypeNum $GUID_FILENAME)
>>FullPath: $FULL_PATH

"@

        # Write to DIP file
        $dipFileStream.Write($dipEntry)

        if ($dipCount % 10 -eq 0) {
            WriteLog "Processed $dipCount attachments..."
        }
    }

    # Write DIP footer
    $dipFooter = @"
>>Dummy Key: Total number of attachments: $dipCount attachments in this file.
END:
"@
    $dipFileStream.Write($dipFooter)

    # Clean up
    $dipFileStream.Close()

    WriteLog ""
    WriteLog "========================================="
    WriteLog "DIP File Creation Complete"
    WriteLog "Total DIP entries created: $dipCount"
    WriteLog "DIP file: $DIPFilePath"
    WriteLog "========================================="

    # Copy DIP file to processing path
    try {
        WriteLog "Copying DIP file to processing path: $DIP_ProcessingPath"

        # Ensure the destination directory exists
        if (-not (Test-Path $DIP_ProcessingPath)) {
            WriteLog "Creating destination directory: $DIP_ProcessingPath"
            New-Item -Path $DIP_ProcessingPath -ItemType Directory -Force | Out-Null
        }

        $destinationFile = Join-Path $DIP_ProcessingPath (Split-Path $DIPFilePath -Leaf)
        Copy-Item -Path $DIPFilePath -Destination $destinationFile -Force

        WriteLog "DIP file successfully copied to: $destinationFile"
    } catch {
        WriteLog "ERROR: Failed to copy DIP file to processing path: $_"
        exit 1
    }

    WriteLog "DIP file creation completed successfully"
    exit 0

} catch {
    WriteLog "ERROR: $_"
    WriteLog $_.ScriptStackTrace
    exit 1
}

#endregion

